version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: env
      - run:
          name: Print the Current Time
          command: apt-get update
      - run:
          name: Print the Current Time
          command: apt-get install curl -y
      - run:
          name: Print the Current Time
          command: curl https://api.github.com/repos/sqerison/generateit/pulls?base=master
